### ISSUE TITLE
Problem  with the app after registration

### ISSUE THREAD

**Issue by wizzzgr** [gridaco/base#37]
Hi,
I am getting the bug with
![image](https://user-images.githubusercontent.com/92581486/137480049-cf9acf3f-dd53-497e-9e1d-675e2a30769a.png)
even after registring and providing the access key. 

app available here
https://digisig.azurewebsites.net/
 
application worked perfectly until friday

**Comment by wizzzgr** [comment]
![image](https://user-images.githubusercontent.com/92581486/137488255-62c14ad6-b1dc-4c35-b985-891e28a282fb.png)
Here you go.

This request worked last week untill friday. The only change I did was adding the api key.
The full request is under

![image](https://user-images.githubusercontent.com/92581486/137488405-36974409-d891-4840-9cc1-b0a030dba966.png)
file
from your website the request works perfectly, only through the post it gets the error

**Comment by wizzzgr** [comment]
Unfortunately it need proxy :)
I tryed the same request through https://app.cors.bridged.cc/
and as you shown in the example it works perfectly.
The same goes when i change POST to GET and copy the request to the brawser, it work.

This request only is failing through your api :).

I tryed adding extra headers, but with or without them, the result is the same. 

I may look for a different proxy, but i got use to yours, because it worked perfectly until your change with the api-key

**Comment by softmarshmallow** [comment]
I'm searching alternative solutions, but unfortunately i can't assure you anything. I'll need information of internal mslogin's logic to find out why the api is failing.

It's also very hard for me to debug this.

I can work on some other temporary solutions, such as whitelisting your domain, so it can work without the api key.
